name: unit tests
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - .github/workflows/docs.yml
      - .github/workflows/unit_tests.yml
      - '**.py'
      - '**.ipynb'
      - uv.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - .github/workflows/docs.yml
      - .github/workflows/unit_tests.yml
      - '**.py'
      - '**.ipynb'
      - uv.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6
        with:
          # Install a specific version of uv.
          version: "0.7.6"
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version-file: ".python-version"

      - name: Install dependencies and check code
        run: |
          cd aieng-topic-impl
          uv venv .venv
          source .venv/bin/activate
          uv sync --all-extras --dev
          uv run pytest -m "not integration_test" tests
